# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  config.vbguest.auto_update = false
  
  config.vm.provision "file",
    source: "~/Courses/DEVOPS/u-vagrant/vagrant/files/git-config",
    destination: "~/.gitconfig"

  config.vm.provision "shell",
    path: "https://raw.githubusercontent.com/echeadle/vagrant/main/scripts/centos-commom.sh"

  config.vm define "web" do |web|
    web.vm.hostname = "web-server"

    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.10.2"
    
    web.vm.provision "shell",
      path: "https://raw.githubusercontent.com/echeadle/vagrant/main/scripts/centos-web.sh"
  end

  config.vm define "db" do |db|
    db.vm.hostname = "database-server"
    db.vm.network "private_network", ip: "192.168.10.3"

    db.vm.provision "shell",
      path: "https://raw.githubusercontent.com/echeadle/vagrant/main/scripts/centos-database.sh"
  end


end
